### ISSUE TITLE
use Tonelli-Shanks with precomputed tables for proof deserialization 

### ISSUE THREAD

**Issue by tanishqjasoria** [NethermindEth/bandersnatch-sharp#49]
Description: https://ihagopian.com/posts/tonelli-shanks-with-precomputed-dlog-tables

Impl1: https://github.com/GottfriedHerold/Bandersnatch/blob/f665f90b64892b9c4c89cff3219e70456bb431e5/bandersnatch/fieldElements/field_element_square_root.go
Impl2:https://github.com/crate-crypto/go-ipa/pull/38

**Comment by namn-grg** [comment]
Hey Tanishq, can you point me to the file once again, where the optimization needs to be done.

Is this the one - [Element.Montgomery.cs#L200](https://github.com/NethermindEth/bandersnatch-sharp/blob/ce98ccf23e602178c6c4cb0e52797dc9d9662f15/src/Nethermind.Verkle/Fields/FpEElement/Element.Montgomery.cs#L200) ?

**Comment by tanishqjasoria** [comment]
yes, but for both FrE and FpE

**Comment by namn-grg** [comment]
got it, going ahead with solving this issue
